[package]
name = "unity_hot_reload"
version = "0.1.15"
edition = "2018"
publish = false


[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
interoptopus = { path = "../../core" }
interoptopus_backend_csharp = { path = "../../backends/csharp" }
