[workspace]
members = [
    "core",
    "backends/c",
    "backends/cpython",
    "backends/csharp",
    "proc_macros",
    "reference_project",
    "examples/complex",
    "examples/hello_world",
    "examples/unity_hot_reload"
]