// Automatically generated by Interoptopus.

#pragma warning disable 0105
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Runtime.InteropServices;
using My.Company;
#pragma warning restore 0105

namespace My.Company
{
    public static partial class Interop
    {
        public const string NativeLib = @"C:\\Users\\john_\\Desktop\\Senior Project CS421\\dell-pravegaapi\\dell-pravegaapi\\Tests\\Rust_Mem_Allocation_Test\\target\\debug\\deps\\testing.dll";
        public string test = Path.Combine(Environment.CurrentDirectory, "");
        static Interop()
        {
        }


        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mem_test_function")]
        public static extern Memtest mem_test_function();

    }

    /// A simple type in our FFI layer.
    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    public partial struct Memtest
    {
        public uint thing;
        public uint thing2;
    }



    public class InteropException<T> : Exception
    {
        public T Error { get; private set; }

        public InteropException(T error): base($"Something went wrong: {error}")
        {
            Error = error;
        }
    }

}
