// Automatically generated by Interoptopus.

#pragma warning disable 0105
using System;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using My.Company;
#pragma warning restore 0105

namespace My.Company
{
    public static partial class Interop
    {
        public const string NativeLib = @"C:\\Users\\john_\\Desktop\\Senior Project CS421\\dell-pravegaapi\\dell-pravegaapi\\Tests\\Rust_Snafu_Test\\target\\debug\\deps\\testing.dll";

        static Interop()
        {
        }


        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "error_checking_test")]
        public static extern uint error_checking_test();

    }



    public class InteropException<T> : Exception
    {
        public T Error { get; private set; }

        public InteropException(T error): base($"Something went wrong: {error}")
        {
            Error = error;
        }
    }

}
