// Automatically generated by Interoptopus.

#pragma warning disable 0105
using System;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using Pravega;
#pragma warning restore 0105

namespace Pravega
{
    public static partial class Interop
    {
        public const string NativeLib = "PravegaCSharp";

        static Interop()
        {
        }


        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "CreateClientFactoryTest")]
        public static extern IntPtr CreateClientFactoryTest();

        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "TestGetRuntime")]
        public static extern IntPtr TestGetRuntime(ref ulong clientFactoryPointer);

    }



    public class InteropException<T> : Exception
    {
        public T Error { get; private set; }

        public InteropException(T error): base($"Something went wrong: {error}")
        {
            Error = error;
        }
    }

}
